"""
VoxShield - Real-Time Audio Transcription Engine
Module: backend.transcription.base
Owner: Keerthi

Domain models, data contracts, and abstract base classes for streaming
and chunk-based speech-to-text processing.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import AsyncIterator, List, Optional
import datetime
import uuid


class SpeakerRole(str, Enum):
    """Identifies speaker channel in call telephony."""
    CALLER = "caller"          # Incoming caller (potential imposter/scammer)
    RECIPIENT = "recipient"    # Internal employee / victim / enterprise agent
    UNKNOWN = "unknown"


class AudioEncoding(str, Enum):
    """Supported telephony and VoIP audio encodings."""
    PCM_16BIT = "pcm_s16le"    # Linear PCM 16-bit little endian (standard 8kHz or 16kHz)
    MULAW = "mulaw"            # G.711 mu-law (standard PSTN telecom)
    ALAW = "alaw"              # G.711 a-law
    WAV = "wav"                # WAV container format


@dataclass
class AudioChunk:
    """Discrete audio buffer slice received from telephony (Rizwan)."""
    session_id: str
    sequence_num: int
    raw_data: bytes
    timestamp_ms: int
    sample_rate_hz: int = 16000
    channels: int = 1
    encoding: AudioEncoding = AudioEncoding.PCM_16BIT
    speaker: SpeakerRole = SpeakerRole.CALLER
    is_last: bool = False

    @property
    def duration_sec(self) -> float:
        """Calculate duration based on 16-bit mono PCM bytes."""
        bytes_per_sample = 2 * self.channels
        if bytes_per_sample == 0 or self.sample_rate_hz == 0:
            return 0.0
        total_samples = len(self.raw_data) / bytes_per_sample
        return total_samples / self.sample_rate_hz


@dataclass
class TranscriptWord:
    """Individual word with timestamp and confidence."""
    word: str
    start_time_sec: float
    end_time_sec: float
    confidence: float = 1.0


@dataclass
class TranscriptSegment:
    """Spoken utterance or chunk generated by speech-to-text."""
    session_id: str
    speaker: SpeakerRole
    text: str
    language: str = "en"
    start_time_sec: float = 0.0
    end_time_sec: float = 0.0
    confidence: float = 1.0
    is_final: bool = True
    words: List[TranscriptWord] = field(default_factory=list)
    segment_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    created_at_iso: str = field(
        default_factory=lambda: datetime.datetime.now(datetime.timezone.utc).isoformat()
    )

    def to_dict(self) -> dict:
        return {
            "segment_id": self.segment_id,
            "session_id": self.session_id,
            "speaker": self.speaker.value,
            "text": self.text,
            "language": self.language,
            "start_time_sec": round(self.start_time_sec, 2),
            "end_time_sec": round(self.end_time_sec, 2),
            "confidence": round(self.confidence, 3),
            "is_final": self.is_final,
            "created_at_iso": self.created_at_iso,
        }


@dataclass
class TranscriptionSessionState:
    """Tracks state of an active call's transcription session."""
    session_id: str
    start_time_iso: str = field(
        default_factory=lambda: datetime.datetime.now(datetime.timezone.utc).isoformat()
    )
    detected_language: str = "en"
    total_audio_sec: float = 0.0
    total_chunks_processed: int = 0
    segments: List[TranscriptSegment] = field(default_factory=list)

    def append_segment(self, segment: TranscriptSegment) -> None:
        self.segments.append(segment)

    def get_full_text(self, speaker: Optional[SpeakerRole] = None) -> str:
        filtered = [
            s.text for s in self.segments
            if (speaker is None or s.speaker == speaker) and s.is_final
        ]
        return " ".join(filtered).strip()

    def get_dialogue_history(self) -> List[dict]:
        """Returns structured dialogue history for downstream engines."""
        return [
            {
                "speaker": s.speaker.value,
                "text": s.text,
                "start": s.start_time_sec,
                "end": s.end_time_sec,
            }
            for s in self.segments if s.is_final
        ]


class BaseTranscriber(ABC):
    """Abstract interface for Speech-to-Text engines."""

    @abstractmethod
    async def transcribe_chunk(self, chunk: AudioChunk) -> List[TranscriptSegment]:
        """Transcribe an isolated audio chunk or speech slice."""
        pass

    @abstractmethod
    async def transcribe_file(
        self,
        file_path: str,
        session_id: str,
        speaker: SpeakerRole = SpeakerRole.CALLER
    ) -> List[TranscriptSegment]:
        """Transcribe a recorded audio file."""
        pass
